version: "3.8"
services:
    server:
        build: ./server
        ports:
            - "8000:8000"
        volumes:
            - ./server:/app
            
    client:
        build:
          context: ./client  # path to project
          dockerfile: Dockerfile
          target: development
        volumes:
          - ./client:/app
        ports:
          - "3000:3000"
