version: '3.8'
services:
  client:
    build:
      context: ./client  # path to project
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"
